### 회원가입
POST localhost:8080/api/v1/auth/naver
Content-Type: application/json

{
  "socialId": "12352",
  "nickname": "testUser"
}

### 내 정보 조회
GET localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 도메인 업데이트
PATCH localhost:8080/api/v1/users/domain
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "domain": "domain1"
}

### 내 정보 업데이트
PATCH localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "nickname": "nickname1"
}

### 유저 탈퇴
DELETE localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}
